name: template_flutter_name_change_example
description: Demonstrates how to use the template_flutter_name_change plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_flavor: ^3.0.1

  # for model
  freezed_annotation: ^0.14.2
  json_serializable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  template_flutter_name_change:
    path: ../
  flutter_flavorizr: ^2.0.0
  flutter_lints: ^1.0.0
  build_runner: ^2.0.5

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  #注)ApplicationIdにハイフンは含められない
  #注)bundleIdにアンダーバーは含められない
  flavors:
    local:
      app:
        name: "Name change（local）"
      android:
        applicationId: "local.template.flutter.name.change"
      ios:
        bundleId: "local.template.flutter.name.change"
    dev:
      app:
        name: "Name change（dev）"
      android:
        applicationId: "dev.template.flutter.name.change"
      ios:
        bundleId: "dev.template.flutter.name.change"
    prod:
      app:
        name: "Name change"
      android:
        applicationId: "template.flutter.name.change"
      ios:
        bundleId: "template.flutter.name.change"
