name: template_flutter_name_change
description: A new flutter plugin project.
version: 0.0.1
homepage: https://pentagon.tokyo/

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  checked_yaml: ^2.0.1
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: com.example.template_flutter_name_change
        pluginClass: TemplateFlutterNameChangePlugin
      ios:
        pluginClass: TemplateFlutterNameChangePlugin
